services:
  - type: static
    name: crypto-monitor
    env: static
    buildCommand: "npm install; npm run dev"
    staticPublishPath: ./
    routes:
      - path: /*
        matchType: prefix
        dest: /index.html
